#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Rigenerato WhatsApp Access Token - Metodo Manuale          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "❌ Metodo via web NON funziona"
echo ""
echo "✅ SOLUZIONE: Usa questo URL direttamente nel browser:"
echo ""
echo "Apri questo link e login con l'account Meta:"
echo "https://developers.facebook.com/apps/1512521410491701/settings/basic/"
echo ""
echo "Oppure:"
echo "https://business.facebook.com/settings/system-users/"
echo ""
echo "Lì troverai il token da copiare."
echo ""
echo "Se non trovi il token, devi:"
echo "1. Creare un NEW SYSTEM USER"
echo "2. Assegnargli i permessi WhatsApp"
echo "3. Generare un nuovo token"
echo ""
