import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/merchant_referral.dart';
import '../utils/logger.dart';
import '../utils/retry.dart';

/// Service per gestire merchant referrals
///
/// Gestisce la creazione, lettura e cancellazione di referral merchant
/// (rider segnala dealer → riceve bonus fisso una tantum).
class MerchantReferralService {
  static final _client = Supabase.instance.client;

  static String? get _riderId => _client.auth.currentUser?.id;

  // ============================================================
  // STREAM SUBSCRIPTION
  // ============================================================

  /// Subscribe to merchant referrals for current rider (real-time)
  static Stream<List<MerchantReferral>> subscribeToReferrals() {
    final riderId = _riderId;
    if (riderId == null) {
      dlog('⚠️ MerchantReferralService: No rider logged in');
      return Stream.value([]);
    }

    return retryStream(
      () => _client
          .from('merchant_referrals')
          .stream(primaryKey: ['id'])
          .eq('referrer_rider_id', riderId)
          .order('created_at', ascending: false)
          .map((data) =>
              data.map((json) => MerchantReferral.fromJson(json)).toList()),
      onReconnect: (attempt, e) {
        dlog('⚡ MerchantReferralService.subscribeToReferrals reconnect attempt $attempt: $e');
      },
    );
  }

  // ============================================================
  // QUERY
  // ============================================================

  /// Get all merchant referrals for current rider
  static Future<List<MerchantReferral>> getReferrals() async {
    final riderId = _riderId;
    if (riderId == null) return [];

    try {
      return await retry(() async {
        final response = await _client
            .from('merchant_referrals')
            .select()
            .eq('referrer_rider_id', riderId)
            .order('created_at', ascending: false);

        return (response as List)
            .map((json) => MerchantReferral.fromJson(json))
            .toList();
      }, onRetry: (attempt, e) {
        dlog('⚡ MerchantReferralService.getReferrals retry $attempt: $e');
      });
    } catch (e) {
      dlog('❌ MerchantReferralService.getReferrals failed: $e');
      return [];
    }
  }

  /// Get merchant referral by ID
  static Future<MerchantReferral?> getReferralById(String referralId) async {
    final riderId = _riderId;
    if (riderId == null) return null;

    try {
      return await retry(() async {
        final response = await _client
            .from('merchant_referrals')
            .select()
            .eq('id', referralId)
            .eq('referrer_rider_id', riderId)
            .maybeSingle();

        if (response == null) return null;
        return MerchantReferral.fromJson(response);
      }, onRetry: (attempt, e) {
        dlog('⚡ MerchantReferralService.getReferralById retry $attempt: $e');
      });
    } catch (e) {
      dlog('❌ MerchantReferralService.getReferralById failed: $e');
      return null;
    }
  }

  /// Get merchant referral by dealer_contact_id
  static Future<MerchantReferral?> getReferralByDealer(
      String dealerContactId) async {
    final riderId = _riderId;
    if (riderId == null) return null;

    try {
      return await retry(() async {
        final response = await _client
            .from('merchant_referrals')
            .select()
            .eq('dealer_contact_id', dealerContactId)
            .eq('referrer_rider_id', riderId)
            .maybeSingle();

        if (response == null) return null;
        return MerchantReferral.fromJson(response);
      }, onRetry: (attempt, e) {
        dlog('⚡ MerchantReferralService.getReferralByDealer retry $attempt: $e');
      });
    } catch (e) {
      dlog('❌ MerchantReferralService.getReferralByDealer failed: $e');
      return null;
    }
  }

  // ============================================================
  // CREATE
  // ============================================================

  /// Create new merchant referral
  ///
  /// Returns referral ID if successful, null if failed.
  static Future<String?> createReferral({
    required String dealerName,
    String? dealerContactId,
    String? phone,
    String? email,
    int bonusAmountCents = 5000, // €50 default
    int thresholdValue = 10, // 10 ordini default
    String? notes,
  }) async {
    final riderId = _riderId;
    if (riderId == null) {
      dlog('❌ MerchantReferralService.createReferral: No rider logged in');
      return null;
    }

    try {
      return await retry(() async {
        final referral = MerchantReferral(
          id: '', // Auto-generated by DB
          referrerRiderId: riderId,
          dealerContactId: dealerContactId,
          dealerName: dealerName,
          dealerPhone: phone,
          dealerEmail: email,
          status: MerchantReferralStatus.pending,
          bonusAmountCents: bonusAmountCents,
          thresholdValue: thresholdValue,
          createdAt: DateTime.now(),
          notes: notes,
        );

        final response = await _client
            .from('merchant_referrals')
            .insert(referral.toInsertJson())
            .select('id')
            .single();

        final referralId = response['id'] as String;
        dlog('✅ MerchantReferralService.createReferral: Created $referralId');
        return referralId;
      }, onRetry: (attempt, e) {
        dlog('⚡ MerchantReferralService.createReferral retry $attempt: $e');
      });
    } catch (e) {
      dlog('❌ MerchantReferralService.createReferral failed: $e');
      return null;
    }
  }

  // ============================================================
  // UPDATE
  // ============================================================

  /// Cancel merchant referral (set status to cancelled)
  ///
  /// Can only cancel if status is pending or active.
  static Future<bool> cancelReferral(String referralId) async {
    final riderId = _riderId;
    if (riderId == null) return false;

    try {
      return await retry(() async {
        await _client
            .from('merchant_referrals')
            .update({
              'status': 'cancelled',
              'cancelled_at': DateTime.now().toIso8601String(),
            })
            .eq('id', referralId)
            .eq('referrer_rider_id', riderId);

        dlog('✅ MerchantReferralService.cancelReferral: Cancelled $referralId');
        return true;
      }, onRetry: (attempt, e) {
        dlog('⚡ MerchantReferralService.cancelReferral retry $attempt: $e');
      });
    } catch (e) {
      dlog('❌ MerchantReferralService.cancelReferral failed: $e');
      return false;
    }
  }

  // ============================================================
  // STATS
  // ============================================================

  /// Get referral stats for current rider
  ///
  /// Returns map with: pending_count, active_count, completed_count, total_bonus_earned_cents
  static Future<Map<String, int>> getStats() async {
    final riderId = _riderId;
    if (riderId == null) {
      return {
        'pending_count': 0,
        'active_count': 0,
        'completed_count': 0,
        'total_bonus_earned_cents': 0,
      };
    }

    try {
      return await retry(() async {
        final response = await _client
            .from('active_merchant_referrals')
            .select()
            .eq('referrer_rider_id', riderId)
            .maybeSingle();

        if (response == null) {
          return {
            'pending_count': 0,
            'active_count': 0,
            'completed_count': 0,
            'total_bonus_earned_cents': 0,
          };
        }

        return {
          'pending_count': response['pending_count'] as int? ?? 0,
          'active_count': response['active_count'] as int? ?? 0,
          'completed_count': response['completed_count'] as int? ?? 0,
          'total_bonus_earned_cents':
              response['total_bonus_earned_cents'] as int? ?? 0,
        };
      }, onRetry: (attempt, e) {
        dlog('⚡ MerchantReferralService.getStats retry $attempt: $e');
      });
    } catch (e) {
      dlog('❌ MerchantReferralService.getStats failed: $e');
      return {
        'pending_count': 0,
        'active_count': 0,
        'completed_count': 0,
        'total_bonus_earned_cents': 0,
      };
    }
  }
}
