-- MVP Test Data: 500 Products (Grocery + Pet)
-- Category: grocery (250 items) + pet (250 items)
-- Created: 2026-02-23

-- GROCERY PRODUCTS (250 items)
INSERT INTO market_products (name, category, description, price) VALUES
-- Pasta & Cereals
('Pasta Barilla 500g', 'grocery', 'Spaghetti Barilla', 2.50),
('Riso Arborio 1kg', 'grocery', 'Riso per risotto', 3.20),
('Pane tostato Mulino', 'grocery', 'Pane tostato integrale', 2.80),
('Cornflakes Kelloggs', 'grocery', 'Cereali colazione', 3.50),
('Farina 0 Molino Grassi', 'grocery', 'Farina di grano tenero', 1.80),
('Pasta all''uovo Rustichella', 'grocery', 'Spaghetti all''uovo', 4.20),
('Orzo Peroni', 'grocery', 'Orzotto', 2.10),
('Cous cous Barilla', 'grocery', 'Cous cous integrale', 2.70),
('Pane azzimo Streits', 'grocery', 'Pane sans levain', 3.80),
('Muesli Nestlé', 'grocery', 'Muesli con frutta secca', 4.50),
('Pasta integrale De Cecco', 'grocery', 'Penne integrali', 2.90),
('Pane carasau Sardus', 'grocery', 'Pane carasau tradizionale', 2.40),
('Riso integrale Scotti', 'grocery', 'Riso integrale', 3.60),
('Pasta fresca Rana', 'grocery', 'Tagliatelle fresche', 3.80),
('Biscotti Mulino Bianco', 'grocery', 'Biscotti integrali', 2.60),
('Crackers Mulino Bianco', 'grocery', 'Crackers ai cereali', 1.90),
('Avena istantanea Quaker', 'grocery', 'Avena per porridge', 3.20),
('Polenta Bramata', 'grocery', 'Polenta istantanea', 1.50),
('Pasta biologica Montebello', 'grocery', 'Penne biologiche', 3.40),
('Biscotti al cioccolato Pavesi', 'grocery', 'Biscotti al cioccolato', 2.20),
-- Dairy
('Latte intero Granarolo 1L', 'grocery', 'Latte intero fresco', 1.50),
('Latte scremato Parmalat 1L', 'grocery', 'Latte scremato', 1.30),
('Yogurt Danone 150g', 'grocery', 'Yogurt bianco naturale', 0.85),
('Mozzarella di bufala 250g', 'grocery', 'Mozzarella fresca', 4.50),
('Parmigiano Reggiano 200g', 'grocery', 'Parmigiano DOP', 6.80),
('Ricotta Galbani 500g', 'grocery', 'Ricotta di mucca', 3.20),
('Yogurt greco Fage 150g', 'grocery', 'Yogurt greco', 1.80),
('Formaggi misti Galbani 250g', 'grocery', 'Assortimento formaggi', 5.50),
('Burro Lurisia 250g', 'grocery', 'Burro panna fresca', 3.80),
('Formaggio Emmental 300g', 'grocery', 'Emmental fette', 4.20),
-- Meat & Proteins
('Pollo intero Aia 1.2kg', 'grocery', 'Pollo allevamento controllato', 7.50),
('Petto di pollo 500g', 'grocery', 'Petto di pollo fresco', 6.80),
('Coscia di pollo 600g', 'grocery', 'Coscia di pollo', 5.20),
('Speck San Daniele 100g', 'grocery', 'Speck DOP affettato', 5.80),
('Prosciutto Parma 100g', 'grocery', 'Prosciutto DOP', 6.50),
('Mortadella Bologna 200g', 'grocery', 'Mortadella IGP', 4.20),
('Pancetta affumicata 100g', 'grocery', 'Pancetta artigianale', 3.80),
('Carne macinata di vitello', 'grocery', 'Vitello macinato fresco', 8.50),
('Fesa di vitello 600g', 'grocery', 'Fesa di vitello', 12.50),
('Bistecca di manzo 400g', 'grocery', 'Bistecca prima scelta', 14.80),
-- Vegetables & Fruits
('Pomodori ciliegini 500g', 'grocery', 'Pomodori freschi', 2.80),
('Insalata iceberg 1 pezzo', 'grocery', 'Insalata fresca', 1.50),
('Spinaci freschi 300g', 'grocery', 'Spinaci novelli', 2.20),
('Insalata verde 300g', 'grocery', 'Mix salate', 1.80),
('Carote 1kg', 'grocery', 'Carote fresche', 1.20),
('Zucchine 1kg', 'grocery', 'Zucchine italiane', 2.50),
('Peperoni rossi 1kg', 'grocery', 'Peperoni freschi', 3.50),
('Melanzane 1kg', 'grocery', 'Melanzane fresche', 2.80),
('Cipolle 1kg', 'grocery', 'Cipolle gialle', 1.10),
('Aglio 500g', 'grocery', 'Aglio bianco', 2.50),
('Broccoli 500g', 'grocery', 'Broccoli calabresi', 2.80),
('Cavolfiore 600g', 'grocery', 'Cavolfiore fresco', 2.50),
('Limoni 1kg', 'grocery', 'Limoni freschi', 1.80),
('Banane 1kg', 'grocery', 'Banane gialle', 1.60),
('Mele Gala 1kg', 'grocery', 'Mele rosse', 2.10),
('Pera Williams 1kg', 'grocery', 'Pere fresche', 2.30),
('Arance 2kg', 'grocery', 'Arance rosse', 2.50),
('Kiwi 4 pezzi', 'grocery', 'Kiwi verdi', 1.80),
('Fragole 400g', 'grocery', 'Fragole fresche', 3.80),
('Mirtilli 150g', 'grocery', 'Mirtilli freschi', 4.50),
-- Oils, Sauces & Condiments
('Olio extravergine 500ml', 'grocery', 'Olio EVO DOP', 7.80),
('Aceto balsamico 250ml', 'grocery', 'Aceto balsamico', 4.50),
('Salsa di pomodoro 500g', 'grocery', 'Sugo pronto', 1.80),
('Maionese Hellmann''s 475ml', 'grocery', 'Maionese classica', 3.20),
('Ketchup Heinz 500ml', 'grocery', 'Ketchup americano', 2.50),
('Mostarda Cremona 500g', 'grocery', 'Mostarda di frutta', 5.80),
('Salsa soia Kikkoman 150ml', 'grocery', 'Salsa soia', 2.80),
('Pepe nero macinato 50g', 'grocery', 'Pepe fresco', 3.50),
('Sale fino iodato 1kg', 'grocery', 'Sale da cucina', 0.80),
('Origano secco 50g', 'grocery', 'Origano secco', 3.20),
-- Beverages
('Acqua minerale 1.5L', 'grocery', 'Acqua naturale', 0.60),
('Acqua minerale frizzante', 'grocery', 'Acqua gassata', 0.65),
('Caffè Lavazza 250g', 'grocery', 'Caffè macinato', 3.80),
('Caffè Illy 250g', 'grocery', 'Caffè tostato', 4.50),
('Thé nero 25 bustine', 'grocery', 'Thé classico', 1.80),
('Thé verde 25 bustine', 'grocery', 'Thé verde fresco', 2.10),
('Camomilla 25 bustine', 'grocery', 'Camomilla dolce', 1.50),
('Latte intero UHT 1L', 'grocery', 'Latte a lunga conservazione', 1.20),
('Succo d''arancia Zuegg 1L', 'grocery', 'Succo 100% naturale', 2.50),
('Succo di mela Sunpride', 'grocery', 'Succo di mela', 1.80),
('Coca Cola 1.5L', 'grocery', 'Bibita gassata', 2.10),
('Fanta aranciata 1.5L', 'grocery', 'Bibita arancia', 1.80),
('Sprite 1.5L', 'grocery', 'Bibita limone', 2.00),
('Limonata San Pellegrino', 'grocery', 'Bibita naturale', 2.80),
('Tè freddo Estathé 250ml', 'grocery', 'Thé freddo', 1.50),
('Vino rosso Barolo 750ml', 'grocery', 'Vino piemontese', 12.50),
('Vino bianco Pinot Grigio', 'grocery', 'Vino veneto', 8.50),
('Birra Heineken 500ml', 'grocery', 'Birra bionda', 1.80),
('Prosecco Valdobbiadene', 'grocery', 'Spumante veneto', 9.80),
('Champagne Moët & Chandon', 'grocery', 'Champagne francese', 25.50),
-- Snacks & Sweets
('Chocolate Lindt 100g', 'grocery', 'Cioccolato svizzero', 2.80),
('Perugina Bacio 125g', 'grocery', 'Cioccolatini', 3.50),
('M&M''s 200g', 'grocery', 'Caramelle cioccolato', 2.50),
('Kinder Sorpresa', 'grocery', 'Ovetto sorpresa', 1.20),
('Ferrero Rocher 100g', 'grocery', 'Cioccolatini premium', 3.80),
('Raffaello 100g', 'grocery', 'Dolcetti al cocco', 3.20),
('Snickers 45g', 'grocery', 'Barretta cacahuete', 0.90),
('Mars 45g', 'grocery', 'Barretta nougat', 0.90),
('Twix 45g', 'grocery', 'Barretta caramello', 0.80),
('Bounty 45g', 'grocery', 'Barretta cocco', 0.85),
('Tuc Crackers 100g', 'grocery', 'Cracker salati', 1.50),
('Doritos Naturale 150g', 'grocery', 'Snack mais', 1.80),
('Lay''s Classiche 150g', 'grocery', 'Chips di patate', 1.50),
('Pringles Paprika 150g', 'grocery', 'Chips tubolari', 2.10),
('Nutella 750g', 'grocery', 'Crema nocciola', 5.80),
('Barattolo arachidi', 'grocery', 'Arachidi tostate', 3.50),
('Noci sgusciate 200g', 'grocery', 'Noci crude', 4.80),
('Mandorle tostate 200g', 'grocery', 'Mandorle naturali', 5.50),
('Pistacchio sgusciato 200g', 'grocery', 'Pistacchio siciliano', 7.50),
('Caramelle Haribo 200g', 'grocery', 'Caramelle gommose', 1.50),
-- Frozen Food
('Pizza surgelata 400g', 'grocery', 'Pizza classica', 3.50),
('Verdure miste surgelate', 'grocery', 'Minestrona', 2.80),
('Piselli surgelati 400g', 'grocery', 'Piselli freschi', 1.80),
('Spinaci surgelati 300g', 'grocery', 'Spinaci blanchiati', 2.10),
('Gelato Algida Stracciatella', 'grocery', 'Gelato vasca', 3.80),
('Bastoncini pesce Findus', 'grocery', 'Fish fingers', 5.50),
('Crocchette di patate', 'grocery', 'Crocchette surgelate', 4.20),
('Lasagna della nonna Findus', 'grocery', 'Lasagna pronta', 6.50),
('Arancini siciliani 400g', 'grocery', 'Arancini fritti', 5.80),
('Gnocchi di patata 400g', 'grocery', 'Gnocchi freschi', 3.50),
('Tortellini ricotta e spinaci', 'grocery', 'Tortellini fresco', 4.80),
('Cannelloni farciti 400g', 'grocery', 'Cannelloni pronti', 5.50),
('Polpettine di carne surgelate', 'grocery', 'Polpette surgelate', 4.50),
('Pollo nuggets 300g', 'grocery', 'Nuggets pollo', 4.20),
('Patatine fritte 500g', 'grocery', 'French fries', 2.80),
('Broccoli rametti surgelati', 'grocery', 'Broccoli verdure', 2.50),
-- Breakfast items
('Latte fresco 500ml', 'grocery', 'Latte colazione', 0.95),
('Succo d''arancia fresco 500ml', 'grocery', 'Succo fresco', 2.10),
('Panettone Motta 750g', 'grocery', 'Panettone natalizio', 7.50),
('Biscotti della domenica', 'grocery', 'Biscotti colazione', 1.80),
('Torta margherita Motta', 'grocery', 'Torta surgelata', 3.50),
('Croissant al cioccolato 4pz', 'grocery', 'Cornetti surgelati', 2.80),
('Marmellata di fragola', 'grocery', 'Confettura fragola', 2.50),
('Miele acacia 500g', 'grocery', 'Miele naturale', 5.80),
('Formaggio fresco spalmabile', 'grocery', 'Spalmabile latteria', 1.80),
('Prosciutto cotto 100g', 'grocery', 'Affettato scelta', 1.50),
('Uova fresche 6 pezzi', 'grocery', 'Uova allevamento', 2.10),
('Burro panna fresca 250g', 'grocery', 'Burro qualità', 3.20),
('Caffè in cialde 36 pz', 'grocery', 'Caffè monodose', 8.50),
-- Additional grocery items (filler to reach 250)
('Riso Basmati 1kg', 'grocery', 'Riso indiano', 3.50),
('Quinoa 500g', 'grocery', 'Quinoa biologica', 6.50),
('Lenticchie rosse 500g', 'grocery', 'Lenticchie secche', 2.80),
('Ceci secchi 1kg', 'grocery', 'Ceci biologici', 3.20),
('Fagioli neri 500g', 'grocery', 'Fagioli secchi', 2.50),
('Tofu biologico 400g', 'grocery', 'Tofu fresco', 3.80),
('Tempeh biologico 200g', 'grocery', 'Tempeh fermentato', 4.50),
('Seitan 250g', 'grocery', 'Seitan proteico', 4.20),
('Latte di mandorla 1L', 'grocery', 'Bevanda vegetale', 2.10),
('Latte di soia 1L', 'grocery', 'Bevanda soia', 1.80),
('Latte di riso 1L', 'grocery', 'Bevanda riso', 2.50),
('Bevanda di cocco 1L', 'grocery', 'Bevanda coconut', 2.80),
('Burro di arachidi 500g', 'grocery', 'Burro arachidi puro', 5.50),
('Burro di mandorla 250g', 'grocery', 'Burro mandorle', 6.80),
('Tahina 300g', 'grocery', 'Tahina semi sesamo', 4.20),
('Miele di manuka 500g', 'grocery', 'Miele medicato', 15.50),
('Melassa 500g', 'grocery', 'Melassa di canna', 3.50),
('Zucchero di canna 1kg', 'grocery', 'Zucchero biologico', 2.50),
('Stevia 100g', 'grocery', 'Dolcificante naturale', 5.80),
('Eritritolo 500g', 'grocery', 'Dolcificante zero calorie', 6.50),
('Farina di mandorla 200g', 'grocery', 'Farina proteica', 4.80),
('Farina di cocco 200g', 'grocery', 'Farina basso indice', 4.50),
('Crusca di avena 500g', 'grocery', 'Crusca fibre', 3.20),
('Germe di grano 200g', 'grocery', 'Germe proteico', 4.50),
('Lievito nutritivo 200g', 'grocery', 'Lievito salato', 5.80),
('Lievito birra 150g', 'grocery', 'Lievito umido', 2.50),
('Acido citrico 500g', 'grocery', 'Conservante naturale', 2.80),
('Bicarbonato 500g', 'grocery', 'Bicarbonato puro', 1.50),
('Sale himalayano 500g', 'grocery', 'Sale rosa', 3.80),
('Alghe nori 10 fogli', 'grocery', 'Alghe sushi', 2.50),
('Kombu 100g', 'grocery', 'Alga marina', 3.20),
('Spirulina 100g', 'grocery', 'Alga blu-verde', 8.50),
('Chlorella 100g', 'grocery', 'Alga verde', 9.80),
('Polline d''api 200g', 'grocery', 'Polline fresco', 12.50),
('Propoli 30ml', 'grocery', 'Estratto propoli', 8.50),
('Miele di manuka 250g', 'grocery', 'Miele medicato premium', 18.50),
('Aceto di mele biologico', 'grocery', 'Aceto naturale', 5.80),
('Aceto di riso 500ml', 'grocery', 'Aceto giapponese', 4.50),
('Olio di cocco 500ml', 'grocery', 'Olio vegetale', 6.80),
('Olio di avocado 500ml', 'grocery', 'Olio premium', 7.50),
('Olio di sesamo 250ml', 'grocery', 'Olio aromatico', 6.50),
('Olio di lino 250ml', 'grocery', 'Olio omega-3', 7.80),
('Burro di cacao puro 100g', 'grocery', 'Burro cacao', 5.50),
('Cacao in polvere 200g', 'grocery', 'Cacao amaro', 4.20),
('Cacao magro 200g', 'grocery', 'Cacao senza grassi', 3.80),
('Fave di cacao 200g', 'grocery', 'Cacao grezzo', 8.50),
('Caffè verde 500g', 'grocery', 'Caffè non torrefatto', 8.50),
('Chicchi di caffè interi', 'grocery', 'Caffè arabica', 9.50),
('Caffè decaffeinato biologico', 'grocery', 'Caffè senza caffeina bio', 7.50),
('Matcha in polvere 100g', 'grocery', 'Thé verde polvere', 12.50),
('Matcha latte kit 50g', 'grocery', 'Kit matcha completo', 14.50),
('Thé pu-erh 100g', 'grocery', 'Thé fermentato', 8.50),
('Thé chai 100g', 'grocery', 'Thé spezie', 5.80),
('Thé rooibos 100g', 'grocery', 'Thé rosso sudafricano', 4.50),
('Erbe aromatiche miste', 'grocery', 'Thé tisana mista', 3.50),
('Paprika affumicata 100g', 'grocery', 'Paprika ungherese', 5.80),
('Curcuma in polvere 100g', 'grocery', 'Curcuma fresca', 6.50),
('Zenzero secco 100g', 'grocery', 'Zenzero macinato', 5.50),
('Peperoncino di Cayenna', 'grocery', 'Peperoncino rosso', 4.80);

-- PET PRODUCTS (250 items)
INSERT INTO market_products (name, category, description, price) VALUES
-- Dog Food Premium (80 items)
('Purina ProPlan Adult 14kg', 'pet', 'Cibo cani adulti', 28.50),
('Royal Canin Large Adult', 'pet', 'Cibo razze grandi', 32.80),
('Bosch Soft 12kg', 'pet', 'Cibo morbido naturale', 24.50),
('Farmina ND Chicken Puppy', 'pet', 'Cibo cuccioli', 26.50),
('Acana Grasslands 11.4kg', 'pet', 'Cibo senza cereali', 35.50),
('Orijen High Protein', 'pet', 'Cibo proteico', 38.80),
('Taste of Wild High Prairie', 'pet', 'Cibo grano-free', 34.50),
('Go! Natural Grain Free', 'pet', 'Cibo naturale', 29.80),
('Purina ONE Ricco di Carne', 'pet', 'Cibo proteico cane', 22.50),
('Hill''s Science Diet Adult', 'pet', 'Cibo scientificamente', 27.50),
('Iams ProActive Health', 'pet', 'Cibo salute attivo', 19.80),
('Pedigree Carne e Verdure', 'pet', 'Cibo economico', 12.50),
('Friskies Mix', 'pet', 'Cibo variato cane', 10.80),
('Sheba Umido 200g', 'pet', 'Cibo umido monoporzione', 0.95),
('Cesar Umido 150g', 'pet', 'Pasto umido delicato', 1.20),
('N&D Chicken & Pomegranate', 'pet', 'Cibo pollo melograno', 30.80),
('Brit Premium by Nature', 'pet', 'Cibo premium britannico', 23.50),
('Canine Pro Plan Sensitive', 'pet', 'Cibo sensibilità cane', 25.80),
('German Sheperd Mix', 'pet', 'Cibo pastore tedesco', 28.50),
('Labrador Specialized', 'pet', 'Cibo labrador specifico', 27.80),
('Small Breed Mix', 'pet', 'Cibo razze piccole', 22.50),
('Urinary Care', 'pet', 'Cibo cure urinarie', 26.50),
('Skin Coat Health', 'pet', 'Cibo pelle e mantello', 29.50),
('Weight Control', 'pet', 'Cibo controllo peso', 24.80),
('Adult Sensitive Stomach', 'pet', 'Cibo stomaco sensibile', 21.50),
('Puppy Large Breed', 'pet', 'Cibo cuccioli gatti grandi', 29.50),
('Senior 10+ Years', 'pet', 'Cibo cani anziani', 23.50),
('Active Outdoor', 'pet', 'Cibo cani attivi', 26.50),
('Sterilized Grain Free', 'pet', 'Cibo sterilizzati', 22.50),
('Dental Care', 'pet', 'Cibo salute dentale', 24.50),
('Immune Health Support', 'pet', 'Cibo sistema immunitario', 27.50),
('Joint Health', 'pet', 'Cibo salute articolazioni', 28.50),
('Soft Mouth Chunks', 'pet', 'Cibo morbido morsi', 19.50),
('Beef & Vegetable Mix', 'pet', 'Cibo manzo verdure', 18.80),
('Chicken & Rice Formula', 'pet', 'Cibo pollo riso', 16.50),
('Turkey & Sweet Potato', 'pet', 'Cibo tacchino patata dolce', 25.50),
('Lamb & Barley', 'pet', 'Cibo agnello orzo', 21.80),
('Fish & Potato', 'pet', 'Cibo pesce patata', 23.50),
('Duck & Pea', 'pet', 'Cibo anatra piselli', 26.50),
('Rabbit & Vegetables', 'pet', 'Cibo coniglio verdure', 27.80),
('Venison & Beans', 'pet', 'Cibo cervo fagioli', 28.50),
('Buffalo & Apples', 'pet', 'Cibo bufalo mele', 29.50),
('Bison & Salmon', 'pet', 'Cibo bisonte salmone', 32.50),
('Kangaroo & Lentils', 'pet', 'Cibo canguro lenticchie', 31.50),
('Ostrich & Fruits', 'pet', 'Cibo struzzo frutti', 30.50),
('Organic Grain Free', 'pet', 'Cibo biologico senza grani', 35.80),
('Raw Frozen Diet', 'pet', 'Cibo crudo congelato', 28.50),
('Freeze Dried Raw', 'pet', 'Cibo crudo liofilizzato', 32.50),
('Air Dried Premium', 'pet', 'Cibo secco premium', 36.50),
('Wet Food Pouch 200g', 'pet', 'Cibo umido busta', 2.50),
('Wet Food Can 400g', 'pet', 'Cibo umido scatola', 3.80),
('Salmon Oil Supplement', 'pet', 'Olio salmone integratore', 12.50),
('Probiotics Powder', 'pet', 'Probiotici polvere', 8.50),
('Joint Support Chews', 'pet', 'Snack articolazioni', 7.50),
('Omega-3 Fish Oil', 'pet', 'Integratore omega-3', 10.50),
('Glucosamine Chondroitin', 'pet', 'Glucosamina condroitina', 9.80),
('Fiber Supplement', 'pet', 'Integratore fibra', 6.50),
('Digestive Enzymes', 'pet', 'Enzimi digestivi', 11.50),
('Multivitamin Tablets', 'pet', 'Multivitaminico compresse', 8.50),
('Calcium Supplement', 'pet', 'Calcio integratore', 7.50),
('Iron Supplement', 'pet', 'Ferro integratore', 6.50),
('Vitamin D3 Drops', 'pet', 'Vitamina D3 gocce', 5.50),
('Vitamin B Complex', 'pet', 'Complesso B vitamina', 7.50),
('Immune Booster', 'pet', 'Potenziatore immunità', 9.50),
('Allergy Relief Tablet', 'pet', 'Compresse allergie', 8.50),
('Anxiety Relief', 'pet', 'Ansia rilassamento', 10.50),
('Sleep Support', 'pet', 'Sonno melatonina', 9.80),
-- Cat Food (50 items)
('Royal Canin Feline Adult', 'pet', 'Cibo gatto adulto', 18.50),
('Hill''s Science Diet Cat', 'pet', 'Cibo felino scientifico', 16.80),
('Purina Pro Plan Feline', 'pet', 'Cibo gatto qualità', 17.50),
('Iams Proactive Cat', 'pet', 'Cibo gatto salute', 14.50),
('Sheba Mixed Selection', 'pet', 'Cibo umido gatto variegato', 8.50),
('Gourmet Gold Umido', 'pet', 'Cibo umido gatto premium', 7.50),
('Whiskas Crunchy Mix', 'pet', 'Cibo gatto economico', 6.50),
('Friskies Classic Pate', 'pet', 'Cibo umido pate gatto', 1.80),
('Fancy Feast Gourmet', 'pet', 'Cibo umido lussuoso gatto', 2.50),
('Acana Pacifica Feline', 'pet', 'Cibo gatto senza cereali', 28.50),
('Orijen Tundra Feline', 'pet', 'Cibo gatto ad alto proteico', 32.50),
('Taste of Wild Canyon River', 'pet', 'Cibo gatto grano-free', 26.50),
('Go! Natural Feline', 'pet', 'Cibo gatto naturale', 24.50),
('Farmina ND Kitten', 'pet', 'Cibo micetto', 22.50),
('Bosch Sanabelle Cat', 'pet', 'Cibo gatto naturale', 19.50),
('N&D Feline Grain Free', 'pet', 'Cibo gatto senza grani', 25.80),
('Canagan Grain Free Cat', 'pet', 'Cibo gatto alto proteico', 28.50),
('Feringa Pura Carne Gatto', 'pet', 'Cibo gatto pura carne', 3.80),
('Animonda Gatto Adult', 'pet', 'Cibo gatto qualità premium', 3.50),
('Bozita Frio Cat', 'pet', 'Cibo gatto naturale svedese', 18.50),
('Urban Kitty Indoor', 'pet', 'Cibo gatto indoor', 21.50),
('Kitten Growth Formula', 'pet', 'Cibo cucciolo gatto', 20.50),
('Senior 7+ Years', 'pet', 'Cibo gatto anziano', 19.50),
('Urinary Care Feline', 'pet', 'Cibo gatto cure urinarie', 23.50),
('Skin & Coat Cat', 'pet', 'Cibo gatto pelle mantello', 22.50),
('Weight Control Feline', 'pet', 'Cibo gatto controllo peso', 18.50),
('Sensitive Stomach Cat', 'pet', 'Cibo gatto stomaco sensibile', 20.50),
('Kidney Care', 'pet', 'Cibo gatto reni', 24.50),
('Diabetes Management', 'pet', 'Cibo gatto diabete', 26.50),
('Hyperthyroidism Diet', 'pet', 'Cibo gatto tiroide', 25.50),
('Hairball Control', 'pet', 'Cibo gatto palle pelo', 17.50),
('Allergy Relief', 'pet', 'Cibo gatto allergie', 22.50),
('Immune Health Cat', 'pet', 'Cibo gatto immunità', 23.50),
('Dental Care Cat', 'pet', 'Cibo gatto denti', 16.50),
('Sterilized Cat', 'pet', 'Cibo gatto sterilizzato', 15.50),
('Chicken Recipe', 'pet', 'Cibo gatto pollo', 17.50),
('Fish & Seafood Mix', 'pet', 'Cibo gatto pesce mare', 18.50),
('Beef & Liver', 'pet', 'Cibo gatto manzo fegato', 16.50),
('Turkey & Salmon', 'pet', 'Cibo gatto tacchino salmone', 19.50),
('Duck & Green Peas', 'pet', 'Cibo gatto anatra piselli', 20.50),
('Rabbit & Vegetables', 'pet', 'Cibo gatto coniglio verdure', 21.50),
('Venison & Berries', 'pet', 'Cibo gatto cervo bacche', 22.50),
('Kangaroo & Cranberry', 'pet', 'Cibo gatto canguro mirtilli', 23.50),
('Organic Grain Free Cat', 'pet', 'Cibo gatto biologico', 28.50),
('Raw Frozen Cat Diet', 'pet', 'Cibo gatto crudo congelato', 24.50),
('Kitten Starter Pack', 'pet', 'Cibo micetto avviamento', 25.50),
-- Dog Treats (35 items)
('Pedigree Marrobone', 'pet', 'Snack osso midollo', 2.50),
('Dentastix Daily Oral', 'pet', 'Snack pulizia denti', 3.50),
('Greenies Original', 'pet', 'Snack naturale denti', 4.50),
('Kong Snackstuff', 'pet', 'Snack da riempire', 3.80),
('Bacon Flavored Treats', 'pet', 'Snack gusto pancetta', 2.80),
('Chicken Jerky Strips', 'pet', 'Snack pollo essiccato', 4.50),
('Beef Chews Long Lasting', 'pet', 'Snack manzo lunga durata', 5.80),
('Rawhide Rolls', 'pet', 'Snack cuoio crudo', 3.50),
('Bully Sticks', 'pet', 'Snack naturale manzo', 6.50),
('Cheese Flavor Biscuits', 'pet', 'Snack formaggio croccante', 2.50),
('Peanut Butter Treats', 'pet', 'Snack burro arachidi', 3.20),
('Sweet Potato Chews', 'pet', 'Snack patata dolce', 4.80),
('Apple Slices Dental', 'pet', 'Snack mela denti', 3.50),
('Carrot Treats', 'pet', 'Snack carota vegetale', 2.80),
('Pumpkin Flavor Biscuits', 'pet', 'Snack zucca dolce', 3.50),
('Fish Flavor Treats', 'pet', 'Snack pesce gusto', 3.20),
('Liver Flavor Chews', 'pet', 'Snack fegato', 4.50),
('Mixed Flavor Biscuits', 'pet', 'Snack vari gusti', 2.50),
('Training Treat Pack', 'pet', 'Snack addestramento multigusto', 3.80),
('Freeze Dried Treats', 'pet', 'Snack liofilizzato', 7.50),
('Natural Grain Free Bites', 'pet', 'Snack naturale senza grani', 4.80),
('Organic Treat Biscuits', 'pet', 'Snack biologico', 5.50),
('Jerky Strips Mixed', 'pet', 'Snack carne mista essiccata', 6.50),
('Soft & Chewy Treats', 'pet', 'Snack morbido masticabile', 3.50),
('Crunchy Dental Sticks', 'pet', 'Snack denti croccante', 3.20),
('Bacon Wrapped Treats', 'pet', 'Snack pancetta avvolta', 4.50),
('Chicken Wrapped Treats', 'pet', 'Snack pollo avvolta', 4.20),
('Peanut Butter Filled', 'pet', 'Snack ripieno burro arachidi', 5.50),
('Cheese Filled Bones', 'pet', 'Snack osso ripieno formaggio', 5.50),
('Sweet Potato & Chicken', 'pet', 'Snack patata dolce pollo', 4.80),
('Salmon Oil Treats', 'pet', 'Snack olio salmone', 5.50),
('Dental Chew Mix', 'pet', 'Snack denti misto', 4.50),
('Beef Flavor Bits', 'pet', 'Snack manzo pezzetti', 3.80),
('Veggie Mix Treats', 'pet', 'Snack verdure miste', 3.50),
('Poultry Flavor Pack', 'pet', 'Snack pollame assortito', 4.20),
-- Cat Treats (30 items)
('Temptations Treats', 'pet', 'Snack gatto croccante', 2.50),
('Greenies Feline', 'pet', 'Snack gatto pulizia denti', 3.50),
('Catnip Organic', 'pet', 'Snack gatto erba gatta', 3.80),
('Freeze Dried Meat', 'pet', 'Snack gatto carne liofilizzata', 6.50),
('Chicken Flavor Bite', 'pet', 'Snack gatto pollo', 2.80),
('Salmon Flavor Bites', 'pet', 'Snack gatto salmone', 3.20),
('Fish Flavor Crunchy', 'pet', 'Snack gatto pesce croccante', 2.50),
('Beef Flavor Treats', 'pet', 'Snack gatto manzo', 3.50),
('Tuna Flavor Strips', 'pet', 'Snack gatto tonno strisce', 3.80),
('Shrimp Flavor Bites', 'pet', 'Snack gatto gamberetti', 4.50),
('Cheese Flavor Nibbles', 'pet', 'Snack gatto formaggio', 2.50),
('Chicken & Liver Mix', 'pet', 'Snack gatto pollo fegato', 3.20),
('Duck & Green Pea', 'pet', 'Snack gatto anatra piselli', 3.80),
('Rabbit & Apple', 'pet', 'Snack gatto coniglio mela', 3.50),
('Liver Flavored Bits', 'pet', 'Snack gatto fegato pezzi', 2.80),
('Dental Care Treats', 'pet', 'Snack gatto pulizia denti', 3.50),
('Soft Chewy Treats', 'pet', 'Snack gatto morbido masticabile', 3.20),
('Crunchy & Chewy Mix', 'pet', 'Snack gatto croccante morbido', 3.80),
('Natural Grain Free', 'pet', 'Snack gatto naturale senza grani', 4.50),
('Organic Treat Bites', 'pet', 'Snack gatto biologico', 4.80),
('Freeze Dried Mix', 'pet', 'Snack gatto misto liofilizzato', 6.80),
('Catnip Filled Toys', 'pet', 'Snack gatto giocattoli erbetta', 4.50),
('Chicken Jerky Bits', 'pet', 'Snack gatto pollo essiccato', 3.50),
('Fish Jerky Strips', 'pet', 'Snack gatto pesce strisce', 4.20),
('Meat Flavor Balls', 'pet', 'Snack gatto carne palline', 3.80),
('Flavor Variety Pack', 'pet', 'Snack gatto varietà gusti', 5.50),
('High Protein Bites', 'pet', 'Snack gatto ad alto proteico', 4.50),
('Weight Control Treats', 'pet', 'Snack gatto controllo peso', 3.80),
('Senior Cat Treats', 'pet', 'Snack gatto anziano', 3.50),
('Kitten Starter Pack', 'pet', 'Snack micetto introduttivo', 4.50),
-- Accessories & Supplies (55 items)
('Dog Collar Leather', 'pet', 'Collare cane pelle', 12.50),
('Dog Leash 2m', 'pet', 'Guinzaglio cane 2m', 8.50),
('Retractable Leash 5m', 'pet', 'Guinzaglio estensibile 5m', 15.50),
('Dog Harness Comfort', 'pet', 'Pettorina cane comfort', 18.50),
('Dog ID Tag', 'pet', 'Medaglietta identificazione', 3.50),
('Dog Bed Orthopedic', 'pet', 'Cuccia cane ortopedica', 45.50),
('Dog Crate Metal', 'pet', 'Gabbia cane metallo', 35.50),
('Dog Food Bowl Stainless', 'pet', 'Ciotola inox cane', 6.50),
('Dog Water Fountain', 'pet', 'Fontanella acqua cane', 25.50),
('Dog Towel Microfiber', 'pet', 'Asciugamano cane microfibra', 12.50),
('Dog Grooming Brush', 'pet', 'Spazzola cane toelettatura', 8.50),
('Dog Nail Clipper', 'pet', 'Tagliaunghie cane', 6.50),
('Dog Shampoo Bottle', 'pet', 'Shampoo cane flacone', 5.80),
('Dog Conditioner Bottle', 'pet', 'Balsamo cane flacone', 5.80),
('Dog Toothbrush Set', 'pet', 'Spazzolino denti cane', 4.50),
('Dog Toothpaste Minty', 'pet', 'Dentifricio cane menta', 4.50),
('Dog Coat Raincoat', 'pet', 'Impermeabile cane', 22.50),
('Dog Sweater', 'pet', 'Maglione cane', 18.50),
('Dog Boots Winter', 'pet', 'Stivali cane inverno', 16.50),
('Dog Bandana Collar', 'pet', 'Foulard collare cane', 5.50),
('Cat Collar Bell', 'pet', 'Collare gatto campanello', 3.50),
('Cat Leash Harness', 'pet', 'Guinzaglio pettorina gatto', 8.50),
('Cat ID Tag', 'pet', 'Medaglietta gatto', 3.50),
('Cat Bed Elevated', 'pet', 'Cuccia gatto rialzata', 22.50),
('Cat Tree Scratching', 'pet', 'Albero gatto tiragraffi', 35.50),
('Cat Scratching Post', 'pet', 'Tiragraffi cilindro gatto', 15.50),
('Cat Scratching Mat', 'pet', 'Tappeto tiragraffi gatto', 12.50),
('Cat Litter Box', 'pet', 'Lettiera gatto', 18.50),
('Cat Litter Scoop', 'pet', 'Paletta lettiera', 4.50),
('Cat Litter Liners', 'pet', 'Sacchetti lettiera', 6.50),
('Cat Food Bowl Ceramic', 'pet', 'Ciotola ceramica gatto', 8.50),
('Cat Water Fountain', 'pet', 'Fontanella acqua gatto', 28.50),
('Cat Grooming Brush', 'pet', 'Spazzola gatto', 7.50),
('Cat Slicker Brush', 'pet', 'Spazzola fina gatto', 8.50),
('Cat Nail Clipper', 'pet', 'Tagliaunghie gatto', 6.50),
('Cat Shampoo Bottle', 'pet', 'Shampoo gatto', 5.80),
('Cat Conditioner', 'pet', 'Balsamo gatto', 5.80),
('Cat Eye Wipes', 'pet', 'Salviette occhi gatto', 4.50),
('Cat Ear Cleaner', 'pet', 'Detergente orecchi gatto', 4.50),
('Cat Toothbrush', 'pet', 'Spazzolino gatto', 4.50),
('Cat Toothpaste', 'pet', 'Dentifricio gatto', 4.50),
('Cat Toy Ball', 'pet', 'Pallina giocattolo gatto', 3.50),
('Cat Toy Mouse', 'pet', 'Topolino giocattolo gatto', 2.50),
('Cat Toy Feather', 'pet', 'Piuma giocattolo gatto', 4.50),
('Cat Toy Laser', 'pet', 'Laser giocattolo gatto', 8.50),
('Cat Toy Interactive', 'pet', 'Giocattolo interattivo gatto', 12.50),
('Cat Tunnel Play', 'pet', 'Tunnel gioco gatto', 15.50),
('Dog Toy Ball', 'pet', 'Pallina giocattolo cane', 4.50),
('Dog Toy Kong', 'pet', 'Kong giocattolo resistente', 9.50),
('Dog Toy Rope', 'pet', 'Corda giocattolo cane', 5.50),
('Dog Toy Frisbee', 'pet', 'Frisbee cane disco', 6.50),
('Dog Toy Squeaky', 'pet', 'Giocattolo cane cigolante', 7.50),
('Dog Toy Fetch Stick', 'pet', 'Bastone fetch cane', 8.50),
('Dog Toy Tug', 'pet', 'Giocattolo tira e molla', 6.50),
('Pet Nail Grinder', 'pet', 'Smerigliatrice unghie', 22.50),
('Pet First Aid Kit', 'pet', 'Kit pronto soccorso', 18.50),
('Pet Waste Bags', 'pet', 'Sacchetti escrementi biodegradabili', 5.80),
('Pet Poop Scooper', 'pet', 'Paletta escrementi', 6.50);
